apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods
  namespace: rbac
subjects:
- kind: ServiceAccount
  name: bot
roleRef:
  kind: Role
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io